---
services:
  weavedeck:
    image: ghcr.io/evolvedevlab/weavedeck:latest
    container_name: weavedeck
    restart: unless-stopped
    ports:
      - "3000:3000" # for diff port "4000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - REBUILD_INTERVAL=10 # in seconds
    volumes:
      - site_data:/app/site
      - ./hugo.toml:/app/site/hugo.toml

volumes:
  site_data:
